### ISSUE TITLE
n64 logo not displaying

### ISSUE THREAD

**Issue by ronilaukkarinen** [anthonycaccese/es-theme-art-book-pocket#1]
Hello! I love this theme, but not all icons displaying (n64, pc), even though on forums it shows they're supported? can you add/fix it? thanks!

**Comment by anthonycaccese** [comment]
Yes totally, I'll try to add in the next few days.  I'll respond here when the changes are up.  Thank you for writing and for checking out the theme!

**Comment by ronilaukkarinen** [comment]
Awesome! works well otherwise on my RaspiBoy (320x240). :)

**Comment by anthonycaccese** [comment]
Hi @ronilaukkarinen just committed the missing logos and now it should be in sync with the base version of the Art Book theme.  Please let me know how it looks on your end when you get a moment.  Thank you!

**Comment by ronilaukkarinen** [comment]
Awesome, looks great! 👍thanks!
